export const POST_SIGNUP_FORM = 'POST_SIGNUP_FORM'
export const SET_DATA_TO_STORE='SET_DATA_TO_STORE'
export const PUSH_TO_PROTECT_PAGE ='PUSH_TO_PROTECT_PAGE'
export const SHOW_ERRORS_SIGNUP='SHOW_ERRORS_SIGNUP'
export const SHOW_ERRORS_LOGIN='SHOW_ERRORS_LOGIN'
export const IS_LOGIN="IS_LOGIN"